---
server:
  image: registry.cn-hongkong.aliyuncs.com/palanqu/easycoding:v0.0.2
  service_name: easycoding-server
  rest_port: 10000
  grpc_port: 10001
  swagger_port: 10002
  restart_on_error: false
  log_dir: ""
  log_level: INFO
  service_monitor: true

# values for https://artifacthub.io/packages/helm/bitnami/mysql
mysql:
  enabled: true
  auth:
    user: root
    rootPassword: root
    database: test
  primary:
    persistence:
      storageClass: "rook-ceph-block"
      size: 8Gi
    service:
      name: easycoding-mysql
      ports:
        mysql: 3306
