---
server:
  image: easycoding:v0.0.1
  service_name: server-svc
  rest_port: 10000
  grpc_port: 10001
  swagger_port: 10002
  restart_on_error: false
  log_dir: ""
  log_level: INFO

# values for https://artifacthub.io/packages/helm/bitnami/mysql
mysql:
  enabled: true
  auth:
    user: root
    rootPassword: root
    database: test
  primary:
    persistence:
      storageClass: "rook-ceph-block"
      size: 8Gi
    service:
      name: easycoding-mysql
      ports:
        mysql: 3306
