---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: easycoding-server
spec:
    selector:
        matchLabels:
            app: easycoding-server
    template:
        metadata:
            labels:
                app: easycoding-server
        spec:
            containers:
            - name: easycoding-server
              image: {{ .Values.server.image }}
              imagePullPolicy: IfNotPresent
              ports:
              - name: rest-port
                containerPort: {{ .Values.server.rest_port }}
              - name: grpc-port
                containerPort: {{ .Values.server.grpc_port }}
              - name: swagger-port
                containerPort: {{ .Values.server.swagger_port }}
              volumeMounts:
              - name: config
                mountPath: /app/config.yaml
                subPath: config.yaml
                readOnly: true
            volumes:
                - name: config
                  configMap:
                      name: easycoding-server-config
                      items:
                      - key: config.yaml
                        path: config.yaml
