---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.server.service_name }}
spec:
    type: ClusterIP
    ports:
    - name: rest-port
      port: {{ .Values.server.rest_port }}
    - name: grpc-port
      port: {{ .Values.server.grpc_port }}
    - name: swagger-port
      port: {{ .Values.server.swagger_port }}
    selector:
        app: easycoding-server
