daemon:
    example_daemon:
        example_daemon: "5"
database:
    create_database: true
    db_name: test
    host: localhost
    password: root
    port: "3306"
    user: root
dev_database:
    create_database: true
    db_name: _migrate_dev
    host: localhost
    password: root
    port: "3306"
    user: root
log:
    dir: ""
    level: INFO
server:
    gateway_port: "10000"
    grpc_port: "10001"
    restart_on_error: false
    swagger_port: "10002"
