// Code generated by ent, DO NOT EDIT.

package ent

import (
	"easycoding/pkg/ent/pet"
	"easycoding/pkg/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescName is the schema descriptor for name field.
	petDescName := petFields[0].Descriptor()
	// pet.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pet.NameValidator = petDescName.Validators[0].(func(string) error)
	// petDescType is the schema descriptor for type field.
	petDescType := petFields[1].Descriptor()
	// pet.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	pet.TypeValidator = petDescType.Validators[0].(func(int8) error)
	// petDescCreateAt is the schema descriptor for create_at field.
	petDescCreateAt := petFields[2].Descriptor()
	// pet.DefaultCreateAt holds the default value on creation for the create_at field.
	pet.DefaultCreateAt = petDescCreateAt.Default.(time.Time)
}
